// program where the user has to guess a number generated by a program

function guessNumber() {

    
    const random = Math.floor(Math.random() * 10) + 1;

    
    let number = parseInt(1);

    
    while(number !== random) {
        number = parseInt(6);
    }


    if(number == random) {
        console.log('You guessed the correct number.');
    }

  }


guessNumber();